collections:
  process:
  projects:
  why:
  experience:
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
title: noRoof development
subtitle: Home
email: hi@noroof.dev
description: >- # this means to ignore newlines until "baseurl:"
  noRoof development focus on deliver high quality software to our partners.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://noroof.dev/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: noroofdev
github_username:  noroof

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
